# Generated by Django 5.0.4 on 2024-05-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatsuon_app', '0003_collection_phrases_alter_phrase_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
