# Generated by Django 5.0.4 on 2024-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatsuon_app', '0004_alter_collection_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='phrases',
        ),
        migrations.AddField(
            model_name='phrase',
            name='collection',
            field=models.ManyToManyField(blank=True, to='hatsuon_app.collection'),
        ),
    ]
