# Generated by Django 5.0.4 on 2024-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatsuon_app', '0008_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
