# Generated by Django 5.0.4 on 2024-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatsuon_app', '0005_remove_collection_phrases_phrase_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='phrases',
            field=models.ManyToManyField(null=True, to='hatsuon_app.phrase'),
        ),
    ]
